language: python
python:
  - '3.7.3'
env:
  -dbParameters='testuser,password123,localhost,5432,testdb'
install: 
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
  - psql -c "CREATE USER testuser WITH PASSWORD 'password123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb to testuser;" -U postgres
  
script: 
  - "python -m pytest tests/"
  - "python -m pytest --cov tests/"
  
after_success:
  - coveralls